name: step_ai
description: "An AI that helps users take the right steps towards optimizing productivity in various tasks."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0
  flutter:
    sdk: flutter

  freezed_annotation: ^2.0.3
  json_annotation: ^4.9.0
  sentry_flutter: ^8.12.0
  
  http: ^1.2.2
  provider: ^6.1.2
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.3
  get_it: ^8.0.2
  flutter_highlight: ^0.7.0

  cupertino_icons: ^1.0.8
  flutter_markdown: ^0.7.4+1
  dio: ^5.7.0
  loading_animation_widget: ^1.3.0
  file_picker: ^8.1.6
  http_parser: ^4.0.2
  url_launcher: ^6.3.1

  image_picker: ^0.8.7+4
  connectivity_plus: ^6.1.1
  google_mobile_ads: ^5.2.0

dev_dependencies:
  flutter_native_splash: ^2.2.10
  flutter_test:
    sdk: flutter
  freezed: ^2.4.2
  build_runner: ^2.3.3
  json_serializable: ^6.6.2

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
     - lib/core/assets/imgs/
     - lib/core/assets/source_unit_images/
flutter_native_splash:
  color: "#ffffff" # Background color of the splash screen
  image: lib/core/assets/imgs/step-ai-logo.png # Path to your splash image
  android: true
  ios: true
  web: false
